"use client"

import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react"
import { onAuthStateChanged } from "firebase/auth"
import { onValue, ref } from "firebase/database"
import { auth, rtdb } from "@/lib/firebase"
import { acceptCall as acceptRequest, declineCall as declineRequest, endCall as endRequest, startCall as startRequest } from "@/lib/call-api"
import { joinChannel } from "@/lib/call-service"

type CallState = "idle" | "calling" | "ringing" | "in-call" | "ended"
type Snapshot = { callId?: string; orderId?: string; direction?: "incoming" | "outgoing"; peerName?: string; status?: string; expiresAt?: number; startedAt?: number; durationSeconds?: number; endReason?: string }
interface CallContextValue { callState: CallState; peerName: string; elapsedSeconds: number; formattedTime: string; isMuted: boolean; endedMessage: string | null; startCall: (orderDocId: string, peerName?: string) => Promise<void>; answerCall: () => Promise<void>; declineCall: () => Promise<void>; endCall: () => Promise<void>; toggleMute: () => Promise<void> }
const Context = createContext<CallContextValue | null>(null)
const format = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`

export function CallProvider({ children }: { children: React.ReactNode }) {
  const [callState, setCallState] = useState<CallState>("idle"), [peerName, setPeerName] = useState(""), [elapsedSeconds, setElapsedSeconds] = useState(0), [isMuted, setIsMuted] = useState(false), [endedMessage, setEndedMessage] = useState<string | null>(null)
  const activeRef = useRef<string | null>(null), snapshotRef = useRef<Snapshot | null>(null), leaveRef = useRef<(() => Promise<void>) | null>(null), muteRef = useRef<((muted: boolean) => Promise<void>) | null>(null), timerRef = useRef<ReturnType<typeof setInterval> | null>(null), ringRef = useRef<ReturnType<typeof setTimeout> | null>(null), audioRef = useRef<HTMLAudioElement | null>(null), offsetRef = useRef(0), stateRef = useRef<CallState>("idle"), uidRef = useRef<string | null>(null)
  const setState = (next: CallState) => { stateRef.current = next; setCallState(next) }
  const stopRing = () => { if (audioRef.current) { try { audioRef.current.pause(); audioRef.current.currentTime = 0 } catch {} } if (ringRef.current) clearTimeout(ringRef.current) }
  const finish = useCallback(async (message: string) => { stopRing(); if (timerRef.current) clearInterval(timerRef.current); await leaveRef.current?.().catch(() => undefined); leaveRef.current = null; muteRef.current = null; setElapsedSeconds(0); setIsMuted(false); setEndedMessage(message); setState("ended"); setTimeout(() => { setEndedMessage(null); setState("idle"); activeRef.current = null }, 2500) }, [])
  const join = useCallback(async (credentials: { appId: string; token: string; channel: string; uid: string }) => { try { const session = await joinChannel(credentials, () => undefined); leaveRef.current = session.leave; muteRef.current = session.setMuted; setState("in-call") } catch { await endRequest(activeRef.current || "").catch(() => undefined); await finish("Microphone access is blocked. Allow it in the browser and try again.") } }, [finish])
  useEffect(() => { const unsubAuth = onAuthStateChanged(auth, (user) => { uidRef.current = user?.uid || null }); return () => unsubAuth() }, [])
  useEffect(() => { let unsub: (() => void) | undefined; const unsubAuth = onAuthStateChanged(auth, (user) => { unsub?.(); if (!user) return; unsub = onValue(ref(rtdb, `user_calls/${user.uid}`), (snap) => { const value = snap.val() as Snapshot | null; if (!value?.callId) return; const previous = snapshotRef.current; snapshotRef.current = value; if (!activeRef.current) { if (["ended", "declined", "missed"].includes(value.status || "")) return; activeRef.current = value.callId; setPeerName(value.peerName || ""); if (value.status === "ringing") { setState(value.direction === "incoming" ? "ringing" : "calling"); if (value.direction === "incoming") { audioRef.current = new Audio("/sounds/call.mp3"); audioRef.current.loop = true; void audioRef.current.play().catch(() => undefined) } if (value.direction === "outgoing") ringRef.current = setTimeout(() => { if (stateRef.current === "calling") void endRequest(value.callId!, "no_answer").then(() => finish("No answer")) }, Math.max(0, (value.expiresAt || Date.now()) - (Date.now() + offsetRef.current))) } } if (activeRef.current !== value.callId) return; if (value.status === "active") { if (stateRef.current !== "in-call") setState("in-call"); if (value.startedAt) setElapsedSeconds(Math.max(0, Math.floor(((Date.now() + offsetRef.current) - value.startedAt) / 1000))) } if (["ended", "declined", "missed"].includes(value.status || "")) { const message = value.endReason === "trip_ended" ? "Trip ended" : value.durationSeconds ? `Call ended · ${format(value.durationSeconds)}` : value.status === "declined" ? "Call declined" : value.direction === "incoming" ? "Missed call" : previous?.startedAt ? "No answer" : "Call cancelled"; void finish(message) } }, (error) => console.error("Call listener error", error)); }); return () => { unsub?.(); unsubAuth() } }, [finish])
  useEffect(() => { if (callState !== "in-call") return; timerRef.current = setInterval(() => { const started = snapshotRef.current?.startedAt; if (started) setElapsedSeconds(Math.max(0, Math.floor(((Date.now() + offsetRef.current) - started) / 1000))) }, 1000); return () => { if (timerRef.current) clearInterval(timerRef.current) } }, [callState])
  useEffect(() => { const offset = onValue(ref(rtdb, ".info/serverTimeOffset"), (s) => { offsetRef.current = s.val() || 0 }); return () => offset() }, [])
  const startCall = async (orderDocId: string, name?: string) => { if (stateRef.current !== "idle") return; setPeerName(name || ""); setState("calling"); try { const credentials = await startRequest(orderDocId); activeRef.current = credentials.callId; await join(credentials) } catch (error) { await finish(error instanceof Error ? error.message : "Unable to start call") } }
  const answerCall = async () => { const id = activeRef.current; if (!id) return; try { await join(await acceptRequest(id)) } catch (error) { await finish(error instanceof Error ? error.message : "Unable to answer call") } }
  const declineCall = async () => { const id = activeRef.current; if (id) await declineRequest(id).catch(() => undefined); await finish("Call declined") }
  const endCall = async () => { const id = activeRef.current; if (id) await endRequest(id).catch(() => undefined); await finish("Call ended") }
  const toggleMute = async () => { const muted = !isMuted; await muteRef.current?.(muted); setIsMuted(muted) }
  return <Context.Provider value={{ callState, peerName, elapsedSeconds, formattedTime: format(elapsedSeconds), isMuted, endedMessage, startCall, answerCall, declineCall, endCall, toggleMute }}>{children}</Context.Provider>
}
export function useCall() { const value = useContext(Context); if (!value) throw new Error("useCall must be used within CallProvider"); return value }
